export const FETCH_ACTIVITY_REQUEST = "FETCH_ACTIVITY_REQUEST";
export const FETCH_ACTIVITY_SUCCESS = "FETCH_ACTIVITY_SUCCESS";
export const FETCH_ACTIVITY_FAILURE = "FETCH_ACTIVITY_FAILURE";
export const ADD_ACTIVITY_REQUEST = "ADD_ACTIVITY_REQUEST";
export const ADD_ACTIVITY_SUCCESS = "ADD_ACTIVITY_SUCCESS";
export const ADD_ACTIVITY_FAILURE = "ADD_ACTIVITY_FAILURE";
export const DELETE_ACTIVITY_REQUEST = "DELETE_ACTIVITY_REQUEST";
export const DELETE_ACTIVITY_SUCCESS = "DELETE_ACTIVITY_SUCCESS";
export const DELETE_ACTIVITY_FAILURE = "DELETE_ACTIVITY_FAILURE";
export const UPDATE_ACTIVITY_REQUEST = "UPDATE_ACTIVITY_REQUEST";
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY_SUCCESS";
export const UPDATE_ACTIVITY_FAILURE = "UPDATE_ACTIVITY_FAILURE";
export const ACTIVITYIDBY_SUCCESS = "ACTIVITYIDBY_SUCCESS";
export const ADD_LEARN_ACTIVITY_REQUEST = "ADD_LEARN_ACTIVITY_REQUEST";
export const ADD_LEARN_ACTIVITY_SUCCESS = "ADD_LEARN_ACTIVITY_SUCCESS";
export const ADD_LEARN_ACTIVITY_FAILURE = "ADD_LEARN_ACTIVITY_FAILURE";
export const FETCH_LEARN_ACTIVITY_SUCCESS = "FETCH_LEARN_ACTIVITY_SUCCESS";
export const FETCH_EXERCISE_ACTIVITY_SUCCESS =
  "FETCH_EXERCISE_ACTIVITY_SUCCESS";
export const FETCH_EXERCISE_ACTIVITY_REQUEST =
  "FETCH_EXERCISE_ACTIVITY_REQUEST";
export const ADD_EXERCISE_ACTIVITY_REQUEST = "ADD_EXERCISE_ACTIVITY_REQUEST";
export const ADD_EXERCISE_ACTIVITY_SUCCESS = "ADD_EXERCISE_ACTIVITY_SUCCESS";
export const ADD_QUIZ_ACTIVITY_REQUEST = "ADD_QUIZ_ACTIVITY_REQUEST";
export const ADD_QUIZ_ACTIVITY_SUCCESS = "ADD_QUIZ_ACTIVITY_SUCCESS";
export const FETCH_QUIZ_ACTIVITY_SUCCESS = "FETCH_QUIZ_ACTIVITY_SUCCESS";
export const FETCH_ATTEMPT_QUIZSCORE_ACTIVITY_SUCCESS =
  "FETCH_ATTEMPT_QUIZSCORE_ACTIVITY_SUCCESS";
export const DELETE_QUIZ_ACTIVITY_SUCCESS = "DELETE_QUIZ_ACTIVITY_SUCCESS";
export const DELETE_QUIZ_ACTIVITY_REQUEST = "DELETE_QUIZ_ACTIVITY_REQUEST";
