export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";
export const FETCH_GETCOURSEBYID_REQUEST = "FETCH_GETCOURSEBYID_REQUEST";
export const FETCH_GETCOURSEBYID_SUCCESS = "FETCH_GETCOURSEBYID_SUCCESS";
export const FETCH_GETCOURSEBYID_FAILURE = "FETCH_GETCOURSEBYID_FAILURE";
